### ISSUE TITLE
Vue guide is not working

### ISSUE THREAD

**Issue by jose1894** [themesberg/flowbite-vue#101]
Hi, I just installed this package following the instructions as it says, in this guide

https://flowbite-vue.com/pages/getting-started.html

but I can't make it works.

I'm using Vue 3.

I ran

<pre>npm i flowbite flowbite-vue</pre>

And I paste this content in the tailwind.conf.js

<pre>
module.exports = {
  content: [
    'node_modules/flowbite-vue/**/*.{js,jsx,ts,tsx}',
    'node_modules/flowbite/**/*.{js,jsx,ts,tsx}'
  ],
  plugins: [
      require('flowbite/plugin')
  ],
  theme: {}
}
</pre>

And it doesn't work, if anybody could help me I will be grateful.

Thanks

**Comment by flprblr** [comment]
It works for me this way.

```
const colors = require('tailwindcss/colors');
const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
        './node_modules/flowbite/**/*.js',
        './node_modules/flowbite-vue/**/*.{js,jsx,ts,tsx}',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography'), require('flowbite/plugin')],
};
```
