### ISSUE TITLE
How can flowbite date picker be implemented? is it currently feasible to do it

### ISSUE THREAD

**Issue by RaniaIsmail** [themesberg/flowbite-vue#110]
I am trying to use flowbite date-range-picker component, but the calendar component is not showing.
any idea on how to implement flowbite date picker?

**Comment by cogor** [comment]
Datepicker component not implemented yet, but we will try to implement it ASAP

**Comment by spmsupun-certscanner** [comment]
@cogor  is this implemented yet?
