### ISSUE TITLE
Improve URL's for docs

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-vue#115]
The final URL should be:

`https://flowbite-vue.com/components/modal/` instead of `https://flowbite-vue.com/components/modal/modal.html`

There are quite a few advantages here:

- the "modal" word does not repeat itself
- prettier URL
- `.html` ending files are redundant

**Comment by cogor** [comment]
> Hey @cogor,
> 
> Do you think this is doable with the current configuration on Heroku? It would be quite important even for SEO purposes.

I think I can fix it with vitepress config
