### ISSUE TITLE
 The engine "node" is incompatible with this module. Expected version "14.x". Got "16.17.0"

### ISSUE THREAD

**Issue by ayitinya** [themesberg/flowbite-vue#119]
Error occured when installing flowbite-vue using yarn add on node

error flowbite-vue@0.0.9: The engine "node" is incompatible with this module. Expected version "14.x". Got "16.17.0"
error Found incompatible module.

**Comment by cogor** [comment]
Hey, fixed in version 0.0.10, now it's nodejs 14 and up
