### ISSUE TITLE
Failed to resolve components

### ISSUE THREAD

**Issue by DubStepMad** [themesberg/flowbite-vue#128]
I followed all the installation docs and end up with the error below.
![VYwvuIxpb](https://user-images.githubusercontent.com/13799856/214153570-e648a69c-332c-4dc5-bc10-68287277860e.png)

Any help would be appreciated.

**Comment by BarishNamazov** [comment]
Did you import the component in your code?
```js
import { Tab } from 'flowbite-vue'
```

**Comment by DubStepMad** [comment]
@BarishNamazov I am yes
