### ISSUE TITLE
permission denied to access property apply when rendering a component inside Modal component

### ISSUE THREAD

**Issue by JonDelWeb** [themesberg/flowbite-vue#132]
Hello, 

I try to render a custom component (empty for now, just a 'p'  tag for testing) inside the Modal flowbite component like this :
```
 <Modal v-if="open" @close="closeModal">
            <template #header>
                <div>
                    <p>Header test</p>
                </div>
            </template>
            <template #body>
                <div>
                   <custom-component"></custom-component>
                </div>
            </template>
            <template #footer>
                <div>
                    <p>The footer test</p>
                </div>
            </template>
  </Modal>
```

But I can't and I get this error : 

`
Uncaught Error: Permission denied to access property "apply"
`

I tried to put my custom component inside 'Suspense' but that's doesn't work...

Any Idea ?

Thanks a lot

**Comment by cogor** [comment]
Couldn't reproduce the problem, if the error happens again, create a new issue
