### ISSUE TITLE
Carousel images not displayed

### ISSUE THREAD

**Issue by bdedardel** [themesberg/flowbite-vue#142]
I have an issue with the default carousel : images are not displayed.

NOK: img class=block absolute top-1/2 left-1/2 w-full -translate-x-1/2 -translate-y-1/2
It works with : img class=w-full

**Comment by cogor** [comment]
Unable to replicate the issue, please verify with the most recent version.

**Comment by bdedardel** [comment]
it works with 1.8.1 :)
