### ISSUE TITLE
Sidebar Properties

### ISSUE THREAD

**Issue by artifex-pro** [themesberg/flowbite-vue#143]
Hi there, for the Sidebar I see no options in the documentation to change links, icons or any properties? I neither can't find it in the module?

**Comment by cogor** [comment]
Hello, the sidebar component is not ready yet, but I'm working on it.

**Comment by aennaco** [comment]
Thanks @cogor,  
  
I'm new with flowbite and nuxt and I'm also trying to edit this sidebar. The ```sidebar.vue.dts``` looks different from your ```sidebar.vue``` and I can't figure out where to edit things. 
  
Thanks in advance!

**Comment by cogor** [comment]
Sidebar component released in version 0.0.17-next.11

**Comment by gabrieldesousah** [comment]
It's possible to toggle to maximize and minimize the sidebar? I want to just show the icons in minized mode and show all in maximized

**Comment by cogor** [comment]
> It's possible to toggle to maximize and minimize the sidebar? I want to just show the icons in minized mode and show all in maximized

Hey, currently we don't have that feature, but I'll add it
