### ISSUE TITLE
How to use Vue Router 4 with flowbite vue links?

### ISSUE THREAD

**Issue by chandlerwilcox88** [themesberg/flowbite-vue#147]
I am using vue router 4 with flowbite vue and I need to figure out how to use it within the nav. Here is an example where I am trying to navigate to the login page. I have the router link slotted inside the navlink component. However, the navlink does not collapse the nav and recognize the new page state. 

Does anyone else use the router with the flowbite nav, if so how did you integrate the two?

Here is my code for the nav:

```js
<Navbar>
    <template #logo>
        <router-link to="/">
            <NavbarLogo link="#" alt="CargoLoot logo" image-url="/assets/logo.png"></NavbarLogo>
        </router-link>
    </template>
    <template #default="{isShowMenu}">
      <NavbarCollapse :isShowMenu="isShowMenu">
        <NavbarLink isActive link="#"><router-link to="/login">{{ $t('navigation.login')}}</router-link></NavbarLink>
        <NavbarLink link="#">{{ $t('navigation.sign_up')}}</NavbarLink>
        <NavbarLink link="#">{{ $t('navigation.monetize')}}</NavbarLink>
        <NavbarLink link="#">{{ $t('navigation.cargoloot')}}</NavbarLink>
        <NavbarLink link="#">{{ $t('navigation.cl_channel')}}</NavbarLink>
        <NavbarLink link="#">{{ $t('navigation.cl_account')}}</NavbarLink>
      </NavbarCollapse>
    </template>
</Navbar>
```

**Comment by roberthgnz** [comment]
@chandlerwilcox88 Currently not possible, I have added a small enhancement to make it supported in https://github.com/themesberg/flowbite-vue/pull/148

**Comment by cogor** [comment]
Hi, you can provide component name to NavbarLink via component prop
`<NavbarLink linkAttr="to" link="/about" component="RouterLink">About</NavbarLink>`
Kudos @roberthgnz 
P.S. You need to use 0.0.11 version or above

**Comment by utkarsh1097** [comment]
```
Hi, you can provide component name to NavbarLink via component prop
<NavbarLink linkAttr="to" link="/about" component="RouterLink">About</NavbarLink>
```

Can this info please also be added to https://flowbite-vue.com/components/navbar and any other component docs that use this pattern?
