### ISSUE TITLE
Toggle component small size

### ISSUE THREAD

**Issue by vasucp1207** [themesberg/flowbite-vue#153]
Changing size classes from ``!w-9 !h-5`` to ``w-9 h-5`` in this PR [commit](https://github.com/themesberg/flowbite-vue/pull/152/commits/99fd8d0b28f2b69c822c805f9d993a8ef9897697]) resulted in inconsistent width behavior for small sizes.

<img width="142" alt="Screenshot 2023-06-18 at 5 50 03 PM" src="https://github.com/themesberg/flowbite-vue/assets/85363195/2eb96ee0-9879-4a07-9307-fec88156ad22">

**Comment by cogor** [comment]
Fixed in 0.0.14
