### ISSUE TITLE
[QUESTION] - Dark Mode Components

### ISSUE THREAD

**Issue by pedrohcarvalhom** [themesberg/flowbite-vue#154]
Hey, I'm using flowbite Forms (still not fully ready, I know), but I just wanna make sure if it's possible to use only in dark mode? My web app does not use dark mode and I wanna change the background input color. 

This one, to be more specific

![image](https://github.com/themesberg/flowbite-vue/assets/109979933/b24f1224-d9d2-41df-8b53-e97b76bc3ee7)

Thanks!

**Comment by cogor** [comment]
Hey, you can just add `dark` class to your `body` and components will work only in dark mode
