### ISSUE TITLE
Vue 3 - js functionality not working

### ISSUE THREAD

**Issue by WieFel** [themesberg/flowbite-vue#16]
Hi,
I am using flowbite with Vue 3 and am having problems with getting javascript functionality (e.g. dropdowns, tooltips, etc.) to work.
Doesn't matter if I try with "plain" `flowbite` (npm package) or install both, `flowbite` + `flowbite-vue`.
Simple flowbite js, like [tooltips](https://flowbite.com/docs/components/tooltips/), just doesn't work. No tooltip is shown...

Example code (taken from first tooltip example):
```vue
<button data-tooltip-target="tooltip-default" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Default tooltip</button>
<div id="tooltip-default" role="tooltip" class="inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 transition-opacity duration-300 tooltip dark:bg-gray-700">
    Tooltip content
    <div class="tooltip-arrow" data-popper-arrow></div>
</div>
```

What could be the problem here?

**Comment by Chank1e** [comment]
You can use this piece of code without installing flowbite-vue at all.
Did you install it correctly with require('flowbite/plugin') inside talwind.config.js like [here ](https://flowbite.com/docs/getting-started/quickstart/)?

**Comment by WieFel** [comment]
> You can use this piece of code without installing flowbite-vue at all. Did you install it correctly with require('flowbite/plugin') inside talwind.config.js like [here ](https://flowbite.com/docs/getting-started/quickstart/)?

Exactly! I followed all of these steps, but when adding the above HTML to my page and hover the button, no tooltip is displayed. The same happens when i try the dropdown from the example code.

It seems that the javascript is just not executed...

**Comment by Chank1e** [comment]
@zoltanszogyenyi maybe you can help here? I don't really know what the reason, because no vue needed here

**Comment by tifennlegoff** [comment]
Hi, i got the same issue with flowbite@1.5.1 but it works when i downgrade to flowbite@1.5.0.
Just for testing, i followed steps on https://flowbite.com/docs/getting-started/vue/. If i run "npm install flowbite" Toggle modal not works, and if i run "npm install flowbite@1.5.0" Toggle modal works.

**Comment by WieFel** [comment]
@tifennlegoff thanks for the help, but for me it still doesn't work.
It seems that still no javascript is executed for me...

**Comment by xeno** [comment]
@tifennlegoff - Can you try now? WIth flowbite ^1.5.2? I just tried and it works for me.

@WieFel  - The instructions are a little odd, as they jump from file to file. You're not replacing the contents of the file with the new code, right? You're just "merging" them?

**Comment by WieFel** [comment]
@xeno still the same.
I am using Vite by the way. Can that somehow be the reason for it not to work?

And yes, of course I am merging the stuff from the instructions with my files.
Even if I import flowbite directly inside the vue component where I want to use the javascript, it just behaves as if there was no flowbite javascript at all.
Maybe I am missing some Vite setting in `vite.config.ts`?

**Comment by xeno** [comment]
Not likely to be an issue with vite. Any chance you can share a test case on a public repository?

**Comment by tifennlegoff** [comment]
Hi, in fact, i just follow tutorial on https://flowbite.com/docs/getting-started/vue/. I try to reproduce with flowbite 1.5.2 but test page still doesn't works. I try on my MacBook 
```
npm --version                                                                                                    
8.6.0
node --version                                                                                                   
v17.3.1
```

and my laptop on Ubuntu 21.
```
npm --version                                                                                                    
8.18.0
node --version                                                                                                   
v18.8.0
```

On my personal project, i don't use Vite.

**Comment by flprblr** [comment]
Same problem here, I tried flowbite 1.5.0-1.5.3 with and without flowbite-vue.

`"devDependencies": {
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",
        "@inertiajs/progress": "^0.2.7",
        "@inertiajs/server": "^0.1.0",
        "@tailwindcss/forms": "^0.5.2",
        "@tailwindcss/typography": "^0.5.2",
        "@vitejs/plugin-vue": "^3.0.0",
        "@vue/server-renderer": "^3.2.31",
        "autoprefixer": "^10.4.7",
        "axios": "^0.27",
        "laravel-vite-plugin": "^0.5.0",
        "lodash": "^4.17.19",
        "postcss": "^8.4.14",
        "tailwindcss": "^3.1.0",
        "vite": "^3.0.0",
        "vue": "^3.2.31"
    },
    "dependencies": {
        "flowbite": "^1.5.3",
        "flowbite-vue": "^0.0.5"
    }`

**Comment by Candlend** [comment]
I have the same problem.

  "dependencies": {
    "@headlessui/vue": "^1.7.3",
    "@heroicons/vue": "^1.0.6",
    "element-plus": "^2.2.19",
    "flowbite": "^1.5.0",
    "flowbite-vue": "^0.0.6",
    "font-awesome": "^4.7.0",
    "vue": "^3.2.41",
    "vue-router": "^4.1.6"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.1.2",
    "autoprefixer": "^10.4.12",
    "postcss": "^8.4.18",
    "tailwindcss": "^3.2.0",
    "typescript": "^4.8.4",
    "vite": "^3.1.8",
    "vite-plugin-vue-component-preview": "^0.3.3",
    "vue-tsc": "^1.0.8"
  }

**Comment by ii64** [comment]
Hi, I got the same issue with `Modal` component. 
The demo code on https://flowbite-vue.com/components/modal/modal.html doesn't pop up any modal, however forcing it by using `Modal` from `flowbite` able to show the modal but interactions (modal close, and action) still broken. 
```ts
onMounted(() => {
  return;
  const targetEl = document.getElementById('defaultModal');

  // options with default values
  const options = {
    placement: 'center',
    backdropClasses: 'bg-gray-900 bg-opacity-50 dark:bg-opacity-80 fixed inset-0 z-40',
    onHide: () => {
      console.log('modal is hidden');
    },
    onShow: () => {
      console.log('modal is shown');
    },
    onToggle: () => {
      console.log('modal has been toggled');
    },
  };
  modal.value = new Modal(targetEl, options);
});
```

I am using `flowbite@1.5.0`, `flowbite-vue@^0.0.6` on `vue@^3.2.41` and `vite`. Did I missed something here?
Also, I tried to check the `flowbite-vue` source on `node_modules` (bundled) it seem did not match with the current source code:

Here, `div` does not have `id` and no `hidden` in `classList`:
https://github.com/themesberg/flowbite-vue/blob/c658c323cd93fb2c7a17de7f23601dd9900d89b8/src/components/Modal/Modal.vue#L4-L7

But on the bundled source code, it appends `id` `defaultModal` and `hidden` class:

<details>
<summary>Bundled</summary>

```js
const _hoisted_1$a = {
  id: "defaultModal",
  tabindex: "-1",
  "aria-hidden": "true",
  class: "hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full"
};
const _hoisted_2$a = /* @__PURE__ */ createStaticVNode('<div class="relative p-4 w-full max-w-2xl h-full md:h-auto"><div class="relative bg-white rounded-lg shadow dark:bg-gray-700"><div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600"><h3 class="text-xl font-semibold text-gray-900 dark:text-white"> Terms of Service </h3><button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="defaultModal"><svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg></button></div><div class="p-6 space-y-6"><p class="text-base leading-relaxed text-gray-500 dark:text-gray-400"> With less than a month to go before the European Union enacts new consumer privacy laws for its citizens, companies around the world are updating their terms of service agreements to comply. </p><p class="text-base leading-relaxed text-gray-500 dark:text-gray-400"> The European Union\u2019s General Data Protection Regulation (G.D.P.R.) goes into effect on May 25 and is meant to ensure a common set of data rights in the European Union. It requires organizations to notify users as soon as possible of high-risk data breaches that could personally affect them. </p></div><div class="flex items-center p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600"><button data-modal-toggle="defaultModal" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">I accept</button><button data-modal-toggle="defaultModal" type="button" class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">Decline</button></div></div></div>', 1);
const _hoisted_3$8 = [
  _hoisted_2$a
];
const _sfc_main$b = /* @__PURE__ */ defineComponent({
  __name: "Modal",
  props: {
    children: {
      type: Array,
      default() {
        return [];
      }
    },
    popup: {
      type: Boolean,
      default: false
    },
    position: {
      type: String,
      default: "center"
    },
    show: {
      type: Boolean,
      default: false
    },
    size: {
      type: String,
      default: "2xl"
    }
  },
  setup(__props) {
    return (_ctx, _cache) => {
      return openBlock(), createElementBlock("div", _hoisted_1$a, _hoisted_3$8);
    };
  }
});
```
</details>

Thanks.

**Comment by potkot** [comment]
Answered a similar question here https://github.com/themesberg/flowbite/issues/231#issuecomment-1332420474

Maybe someone will help

**Comment by victorh5** [comment]
@WieFel I am with the same problem, did you find any solution?

I am using Vite and Vue 3.

versions of flowbite installed on my project:
`"flowbite": "^1.5.5"`
`"flowbite-vue": "^0.0.9"`

**Comment by WieFel** [comment]
> @WieFel I am with the same problem, did you find any solution?
> 
> I am using Vite and Vue 3.
> 
> versions of flowbite installed on my project:
> `"flowbite": "^1.5.5"`
> `"flowbite-vue": "^0.0.9"`

Unfortunately no...
I just tried to use other approaches for the js functionality, like implementing it manually or use vue's material components.

**Comment by cogor** [comment]
Outdated issue

**Comment by YusronAminullah** [comment]
In file main.js you add this : 

```
import 'flowbite/dist/flowbite.js';
import 'flowbite/dist/flowbite.css';
import './index.css'
```

And in file tailwind.config.js you add this : 

```
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    './node_modules/flowbite/**/*.{js,jsx,ts,tsx}'
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('flowbite/plugin')
  ],
}
```
If you use vite. Open vite.config.js and add this : 

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import flowbite from 'flowbite/plugin'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), flowbite()],
})
```
Open file where you add component flowbite. In this, i use sidebar dropdown from flowbite. In some cases the possibility is the same, including modal : 

in <script> :

```
import Sidebar from './Sidebar.vue';
import { onMounted } from 'vue';
import { Dropdown } from 'flowbite';

onMounted(() => {
  // Initialize all dropdowns
  const dropdownElements = document.querySelectorAll('[data-dropdown-toggle]');
  dropdownElements.forEach(triggerEl => {
    const targetEl = document.getElementById(triggerEl.getAttribute('data-dropdown-toggle'));
    new Dropdown(targetEl, triggerEl);
  });
});
```

And in <template> : 

`<Sidebar />`
