### ISSUE TITLE
close modal when clicking outside

### ISSUE THREAD

**Issue by badhri17** [themesberg/flowbite-vue#170]
Hi I am thinking to contribute to this project by adding this functionality :
touching outside the modal close it automatically 

my plan is to add a dismissableMask (boolean) props in the modal component that specifies if clicking the modal background should hide the dialog or not

**Comment by cogor** [comment]
I think this is a great idea, only instead of a prop you need to use an event when the wrapper is clicked, I think an appropriate name for this event is click:outside

**Comment by badhri17** [comment]
I agree with you and perhaps we can later add an example in the documentation in the modal page
so should I start working on this feature?

**Comment by cogor** [comment]
Hi, I have implemented your idea and made several improvements. I added a click outside event and made some other enhancements.
Wait for it in next release(0.0.16)
