### ISSUE TITLE
Use of tailwind-merge

### ISSUE THREAD

**Issue by LockBlock-dev** [themesberg/flowbite-vue#176]
The library currently lacks a way to customize the components classes.  
It would be great to use [tailwind-merge](https://github.com/dcastil/tailwind-merge) like [flowbite-react](https://github.com/themesberg/flowbite-react/pull/816) and [flowbite-svelte](https://github.com/themesberg/flowbite-svelte/pull/850) did in my opinion. What do you think?

**Comment by Cry0nicS** [comment]
@LockBlock-dev from what I could see, you can set all the tw classes you want to use to customize a component as _!important_. 

Example
```ts
<Navbar class="!bg-pink-300 !text-yellow-300">
   // ... content
</Navbar>
```
Would give you what you'd expect:
![image](https://github.com/themesberg/flowbite-vue/assets/29982205/35d3c6fe-06a1-43a8-bb42-633de2d38d1a)

It's not a great solution, there are drawbacks, but it would allow you customize the components until / without tailwind-merge.
