### ISSUE TITLE
Accordion: How to ensure all items are closed/collapsed initially

### ISSUE THREAD

**Issue by aarondt1** [themesberg/flowbite-vue#178]
When the accordion is rendered in the UI the first element is always opened. I saw that there is away to ensure all elements to be always open ("always-open") but is there also a way to ensure that they are always closed - meaning the first element is also closed initially?

**Comment by ExPlo1t-php** [comment]
> When the accordion is rendered in the UI the first element is always opened. I saw that there is away to ensure all elements to be always open ("always-open") but is there also a way to ensure that they are always closed - meaning the first element is also closed initially?

I wonder if you have found a workaround for this?

**Comment by cogor** [comment]
In the next couple days, I'll be adding a new prop to control this.

**Comment by cogor** [comment]
Fixed in version 0.0.17-next.1
Docs: https://flowbite-vue.com/components/accordion#closed-first-item
