### ISSUE TITLE
simplifyTailwindClasses omits classes when used with an empty string

### ISSUE THREAD

**Issue by danielbinsmaier** [themesberg/flowbite-vue#181]
When using e.g. `Input` component with the property `disabled` set to `false`, `simplifyTailwindClasses` will be called like this: `simplifyTailwindClasses('border border-gray-300...', '...', '')`. As you can see, the last string is empty. This will then lead to `border` CSS class being obmitted.

To reproduce, simply use the Input component without any properties (use the defaults). Then inspect the element and you will see there is no `border` class.

**Comment by cogor** [comment]
Released in version 0.0.17-next.2
