### ISSUE TITLE
Fix Flowbite-vue.com/components/  Tabs, ListGroup and Toast Demo => on click is show 404 Page Error

### ISSUE THREAD

**Issue by ibrahmad18** [themesberg/flowbite-vue#187]
ListGroup, Tabs and Toast is not working on https://flowbite-vue.com/components/

**Comment by cogor** [comment]
Where you found this link?

**Comment by cogor** [comment]
Can't reproduce the problem

**Comment by ibrahmad18** [comment]
Thank you for the bug fixing now is working fine .
