### ISSUE TITLE
Component: Textarea - Invalid wrapper tag name

### ISSUE THREAD

**Issue by caplockon** [themesberg/flowbite-vue#229]
The wrapper should be a `div`, and the label should be a `label`. Please check at file `src/components/Textarea/Textarea.vue` line 2
![image](https://github.com/themesberg/flowbite-vue/assets/22407270/bd36a0f0-44f2-4eda-b760-e8859f1faac5)

**Comment by cogor** [comment]
This is a valid tag, it's done so to avoid using 'for' for label and 'id' for textarea
