### ISSUE TITLE
Trailing space prevents checkout on Windows

### ISSUE THREAD

**Issue by snoopen** [themesberg/flowbite-vue#234]
env.d.ts has a trailing space preventing git checkout on Windows:
`error: invalid path 'env.d.ts '`

You can see there is a trailing space by navigating to the file online:
`https://github.com/themesberg/flowbite-vue/blob/main/env.d.ts%20`

**Comment by Sqrcz** [comment]
@snoopen thank you for finding this one...  fix is merged.
