### ISSUE TITLE
Off by one error in pagination with table layout

### ISSUE THREAD

**Issue by snoopen** [themesberg/flowbite-vue#246]
The example shown in the docs has 20 items per page, so should read "Showing 1 to 20 of 998". However it reads "1 to 21". Page two will read "21 to 41" and so on.

This also affects the final page, except when the number of items is a multiple of the per page. For example, 1000 items and 20 per page will correctly read "Showing 981 to 1000".

**Comment by Sqrcz** [comment]
fix merged, thank you @snoopen 🙌
