### ISSUE TITLE
Too many styles

### ISSUE THREAD

**Issue by new-user-name** [themesberg/flowbite-vue#252]
Hi,
I did everything by the book, and the resulting css is huge. In the manual I see lines
```
  content: [
    'node_modules/flowbite-vue/**/*.{js,jsx,ts,tsx}',
    'node_modules/flowbite/**/*.{js,jsx,ts,tsx}'
  ],
```
Obviously, Tailwind pulls every style found in the files. Is there any way to include only the styles I use in the project?.. For example, I use only fwb-select. How can I import only the related styles?.. I think the problem is that Tailwind does not now during compilation stage which styles will be in use, so we import all 7000 lines of Flowbite.

**Comment by cogor** [comment]
Hey, from version 0.1.2 you can add components you use into tailwind.config.js
It's looks like
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    'node_modules/flowbite-vue/**/FwbModal.vue',
    'node_modules/flowbite-vue/**/FwbAlert.vue',
    'node_modules/flowbite-vue/**/FwbSidebar.vue',
    'node_modules/flowbite-vue/**/FwbSidebarItem.vue',
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  plugins: [
    require('flowbite/plugin')
  ],
}
```
