### ISSUE TITLE
Broken link: README.md introduction link broken

### ISSUE THREAD

**Issue by pippinmole** [themesberg/flowbite-vue#253]
Reference: [https://github.com/themesberg/flowbite-vue/blob/main/README.md?plain=1#L52](https://github.com/themesberg/flowbite-vue/blob/main/README.md?plain=1#L52).

The link when clicked, takes you to a 404 not found page.

Should link to: [https://flowbite.com/docs/getting-started/introduction/](https://flowbite.com/docs/getting-started/introduction/).

Let me know if you want me to make a PR for this.

**Comment by cogor** [comment]
Thank you, fixed
