### ISSUE TITLE
FwbFileInput accept props not working

### ISSUE THREAD

**Issue by callixte** [themesberg/flowbite-vue#284]
Hello there,

I am using v0.1.4 and the `FwbFileInput` component.
I tried to add an `accept` field as it is one of the props now. But it doesn't work and it is passed on to the first div as if not recognized as a prop.

I checked the code in my node_modules and noticed something weird: the `src/components/FwbFileInput/FwbFileInput.vue` has the correct props, but the `dist/components/FwbFileInput/FwbFileInput.vue.d.ts` doesn't.

Thanks in advance for your help.

**Comment by Sqrcz** [comment]
Thank you for catching this... it looks like release was not build properly... :/

I'm AFK for the weekend already... but I'll fix it as soon as I'm back on Monday.

**Comment by Sqrcz** [comment]
Hey @callixte,

[v0.1.5](https://github.com/themesberg/flowbite-vue/releases/tag/v0.1.5) was just released please check if it fixed this issue.
