### ISSUE TITLE
Tooltip background is not applying 

### ISSUE THREAD

**Issue by karthik-propvr** [themesberg/flowbite-vue#286]
Dear fellow developers I have started using this package for past 1 week, we are trying some components  for our product.
So on tooltip component the background is not getting applied even we tried with all theme like (light and dark), Here I am attaching the code and screenshot for you reference 

`<fwb-tooltip placement="left">
    <template #trigger>
        <fwb-button class="bg-white hover:border-2 hover:border-gray-400" color="default" pill square>
           Toggle Button
        </fwb-button>
    </template>
    <template #content>
             Toggle button Tooltip
    </template>
</fwb-tooltip>`

![image (2)](https://github.com/themesberg/flowbite-vue/assets/130982201/ec0c5c75-2583-4bf4-a56a-0001b7315920)

Kindly let me know what we are missing out on this code..
Thanks in advance!!

**Comment by DevelopmentNightmare** [comment]
I have the same issue.

**Comment by Sqrcz** [comment]
Hey,

There was an issue with previous release... [v0.1.5](https://github.com/themesberg/flowbite-vue/releases/tag/v0.1.5) should fix the above issue... pleas check it and let me know.

**Comment by Sqrcz** [comment]
FYI: @DevelopmentNightmare, @karthik-propvr 

I'm closing this one... but if you're still having an issue with it please let me know.
