### ISSUE TITLE
white label not visible in Toggle component

### ISSUE THREAD

**Issue by TissyashriS** [themesberg/flowbite-vue#297]
I tried implementing the toggle component in my project using Flowbite version 2.3.0 and encountered an issue: the label with white text color is not visible. This issue is in all the type of toggles - Disabled toggle, colors , default toogle.

My code snippet 
![image](https://github.com/themesberg/flowbite-vue/assets/154225046/51e145c7-6f67-45c3-af26-a84842dc1102)

output: 
![image](https://github.com/themesberg/flowbite-vue/assets/154225046/c3a0e988-ab13-4413-9dcf-c2d370436a89)   
![image](https://github.com/themesberg/flowbite-vue/assets/154225046/4e529ef4-733e-4e0c-84cb-99ff4912e9e0)

**Comment by ogzcode** [comment]
Hi,
It works in the stackblitz link below. You do not need to use the `initFlowbite()` function. That function is there to write your own event listeners. You can look at the doc.

[Stackblitz Link](https://stackblitz.com/edit/vitejs-vite-5ajp7r?file=src%2FApp.vue&terminal=dev)
[initFlowbite() Doc](https://flowbite.com/docs/getting-started/quickstart/#init-functions)

@zoltanszogyenyi @robert1508 please close this issue

**Comment by Sqrcz** [comment]
Thank you for the example @ogzcode .

Closing as it's working when implemented according to the documentation. ;)
