### ISSUE TITLE
Set up hosting for flowbite-vue.com

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-vue#3]
Hey @Chank1e, @ralphschuler,

We could host this on [Flowbite Vue](https://flowbite-vue.com) with any hosting platform that you think that plays nicely with Vue.

Let me know, we'll cover the costs.

Cheers,
Zoltan

PS: you can join our [Discord Server](https://discord.gg/4eeurUVvTy) and there's quite a bit of Vue.js community there that can get involved with the development of this library.

You can just DM me (zoltanszogyenyi) and get things started.

**Comment by xeno** [comment]
It appears this is done? Or is the current site hosted somewhere else?

**Comment by ralphschuler** [comment]
Closing it as https://flowbite-vue.com/ exists.
