### ISSUE TITLE
component: Card

### ISSUE THREAD

**Issue by xeno** [themesberg/flowbite-vue#54]
The following tasks need to be complete for this component:

- [ ] Create Card component
  * Follow the examples in [the Flowbite docs](https://flowbite.com/docs/components/card/)
- [ ] Add documentation
  * Include examples matching the Flowbite docs
  * Use [existing documentation](https://flowbite-vue.com/components/button/button.html) as a guide

**Comment by AhnafAhamed** [comment]
Hi @xeno, I would like to work on this issue.

**Comment by xeno** [comment]
Go for it. All help is appreciated. :)

**Comment by AhnafAhamed** [comment]
@xeno I think we can close this issue, since it's completed
