### ISSUE TITLE
component: Modal

### ISSUE THREAD

**Issue by xeno** [themesberg/flowbite-vue#56]
The following tasks need to be complete for this component:

- [ ] Create Modal component
  * Follow the examples in [the Flowbite docs](https://flowbite.com/docs/components/modal/)
  * Use the "JavaScript Behaviour" section as a guide for params to be made available
- [ ] Add documentation
  * Include examples matching the Flowbite docs
  * Use [existing documentation](https://flowbite-vue.com/components/button/button.html) as a guide

**Comment by MartinNiederl** [comment]
Is it known approximately when the updated components will be published?
The pull request was merged more than a month ago, but there was no update on [npmjs.com](https://www.npmjs.com/package/flowbite-vue) yet and this issue was not adjusted either.

**Comment by cogor** [comment]
Modal component added in version 0.0.7
