### ISSUE TITLE
Cannot find types

### ISSUE THREAD

**Issue by rcedcabrera** [themesberg/flowbite-vue#84]
Hi I encountered an error while building the app. May I know how can I fix this?

![image](https://user-images.githubusercontent.com/88480929/190696847-a7c7f70f-7001-4349-b618-75a3deb58a09.png)

**Comment by cogor** [comment]
Hi, I updated version on npm, may you check do you see that error now?

**Comment by rcedcabrera** [comment]
Hi I got this error again. using yarn in new project.

![image](https://user-images.githubusercontent.com/88480929/211537091-158f777a-8c74-4a17-b676-e2158266a5e7.png)
