### ISSUE TITLE
Updated NPM package?

### ISSUE THREAD

**Issue by binaryfire** [themesberg/flowbite-vue#91]
Hi guys

I've bought the Flowbite Pro team license in anticipation of the official Vue release. We'd like to start developing with the components now but the last NPM release was in July: https://www.npmjs.com/package/flowbite-vue.

Would it be possible to push out another release with the most recent updates? Or should we install using
`npm i https://github.com/themesberg/flowbite-vue`  instead?

Cheers

**Comment by cogor** [comment]
Hi, I updated version on npm, but part of components in development yet

**Comment by binaryfire** [comment]
@cogor Great, thank you!
