### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by the-overdriven** [themesberg/flowbite-vue#94]
This repository is called "flowbite-vue", but in your readme you have links pointing to https://flowbite-react.com/ - wtf?

Also how am I supposed to use this? https://flowbite-vue.com/components/table/table.html
How do I customize the data? There are no props listed, nothing. Is this even usable?

**Comment by zoltanszogyenyi** [comment]
Hey there! We'll change the Flowbite React in the readme - the .md file was forked from that linrary.

The table component is not yet finished, hence the lack of props and documentation.

It's a library still in progress and everyone is free to contribute to speed up the process.

Cheers!

**Comment by cogor** [comment]
Hi, thank you for your question, I updated links in readme.md.
You can watch table component progress in issue #70
